# Generated by Django 4.2 on 2023-05-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_referral_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='user.customer'),
        ),
    ]
