# Generated by Django 4.2 on 2023-05-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_referral_referral_code_alter_referral_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referral',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
