# Generated by Django 4.2 on 2023-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='customer',
        ),
        migrations.AddField(
            model_name='referral',
            name='customer',
            field=models.ManyToManyField(related_name='referrals', to='user.customer'),
        ),
    ]
