# Generated by Django 4.2 on 2023-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_referral_customer_referral_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
