# Generated by Django 4.2 on 2023-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_referral_referral_code_customer_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_code_other',
            field=models.IntegerField(null=True),
        ),
    ]
