# Generated by Django 4.2 on 2023-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customer_referral_code_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
