# Generated by Django 4.2 on 2023-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customer_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_customer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
